# The build's view of Maged Michael's hazard pointers (mm_hp/, generated by
# `make imports` in this directory; ../third_party.mk) and of the headers built
# on them, written once for the three Makefiles whose targets link mm_hp: this
# directory's own (`include mm_hp.mk`) and its consumers' in ../SharedPtr and
# ../LockFreeList (`include ../IntrSharedPtr/mm_hp.mk`). A new mm_hp file, or a
# new header of this project on top of mm_hp, is added here, once.
#
# Defines, every path spelt as the including Makefile must spell it:
#   MM_HP_PREFIX  this file's directory as the includer names it, with a
#                 trailing slash; empty when the includer is in this directory,
#                 so that this directory's commands keep plain mm_hp/... paths.
#   HP_SOURCES    mm_hp's one source file. Every target that links mm_hp lists
#                 it twice: as a prerequisite, so editing mm_hp.cpp rebuilds the
#                 target, and explicitly in the recipe after $<, so mm_hp.cpp is
#                 compiled in the same command with the same flags
#                 (optimization, sanitizer) as the TU it links with; a
#                 separately built object would need one build per flavour and
#                 per-flavour rules. Compiling it again per target is cheap
#                 (~240 lines). Linux only: mm_hp issues membarrier(2).
#   MM_HP_STAMP   mm_hp/SOURCE.txt, written when mm_hp/ is made. It is on
#                 HP_HEADERS so that remaking mm_hp/ rebuilds everything that
#                 uses it: the generated files keep upstream's old dates.
#   HP_HEADERS    what a target that uses intr_shared_ptr_hp or the drain helper
#                 depends on besides HP_SOURCES: the pointer, the drain helper,
#                 mm_hp's headers and the stamp. Prerequisites only: the recipes
#                 pass $<, never $^.
# and the rule that makes the generated files come with the stamp.
#
# Not here: how the stamp is made. This directory's Makefile makes it (its
# `imports`, with ../third_party.mk's recipe); a consumer's rule for it asks this
# directory, `$(MAKE) -C ../IntrSharedPtr imports`, and never makes it itself.

# Taken first, while this file is still the last word of MAKEFILE_LIST.
MM_HP_PREFIX := $(filter-out ./,$(dir $(lastword $(MAKEFILE_LIST))))

HP_SOURCES := $(MM_HP_PREFIX)mm_hp/mm_hp.cpp
MM_HP_STAMP := $(MM_HP_PREFIX)mm_hp/SOURCE.txt
MM_HP_GENERATED_HEADERS := $(addprefix $(MM_HP_PREFIX)mm_hp/,mm_hp.hpp asymmetric_fence.hpp)
HP_HEADERS := $(addprefix $(MM_HP_PREFIX),intr_shared_ptr_hp.h hp_drain.h hp_drain_gtest.h) \
              $(MM_HP_GENERATED_HEADERS) $(MM_HP_STAMP)

# The generated files come with the stamp (an empty recipe: making the stamp
# makes them). Without this rule a fresh tree would stop at "No rule to make
# target .../mm_hp/mm_hp.cpp" instead of making mm_hp/. Order-only (`|`): the
# stamp must exist before the files are looked at, but its date does not make
# them out of date -- they keep upstream's older dates, so a normal
# prerequisite would "remake" them on every run, which a real build shrugs off
# (make looks at the dates again) but which makes `make -n` list every compile
# and `make -q` report out of date forever. A remade mm_hp/ still rebuilds its
# users: they list MM_HP_STAMP itself (HP_HEADERS).
$(HP_SOURCES) $(MM_HP_GENERATED_HEADERS): | $(MM_HP_STAMP) ;
