#!/bin/bash
# Makes SharedPtr's copies of other people's code from their upstream clones.
#
# Why: ThirdParty/<name> (the git clones at the top of the work tree) is the one
# source of third-party code; what the build uses is derived from it by this
# script and a patch of our changes kept next to the output. Neither output
# directory is tracked by the repository (both are in .gitignore), so a fresh
# tree runs this script once before `make`, and again after the patches change.
#
#   mm_hp/                       Maged Michael's hazard pointers
#                                (github.com/magedm/mm_hp), used by intr_shared_ptr_hp
#                                and hp_drain.h; patch mm_hp.patch.
#   lock_free_shared_ptr/parlay/ Daniel Anderson's parlay::shared_ptr and hazard
#                                pointers (github.com/DanielLiamAnderson/atomic_shared_ptr),
#                                which our lock_free_shared_ptr/atomic_shared_ptr.hpp is
#                                built on, plus ParlayLib's headers for its pool allocator
#                                (github.com/cmuparlay/parlaylib), unmodified; patch
#                                lock_free_shared_ptr/parlay.patch (folly replaced by
#                                standard equivalents, the list's Harris mark stripped in
#                                parlay's reference counting).
# Each patch's header says what each change is for.
#
# Each output is built in a temporary directory, records its sources in
# SOURCE.txt, and then replaces the old directory. A clone at another commit than
# the one pinned below fails: the patch may not fit it; refresh the patch first.
#
# Usage: ./make_third_party.sh [mm_hp] [parlay]   (no argument: both; from anywhere)
# Clone locations: THIRD_PARTY (default <top of the work tree>/ThirdParty), with
# HazardPtr, AtomicSharedPtr and ParlayLib in it.
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
THIRD_PARTY=${THIRD_PARTY:-$(cd "$HERE/.." && pwd)/ThirdParty}
# The upstream commits the patches were made against.
HP_COMMIT=b26e5edc779bf2afaea821549c04bf0a07b20f11       # HazardPtr (mm_hp)
ASP_COMMIT=3c213ef8a437b419171f901e640ddfdd6056d905      # AtomicSharedPtr
PARLAY_COMMIT=51017699dcc421f80479cdb238d3092233ad0d26   # ParlayLib

# clone_at <name> <commit>: prints the clone's path; fails unless it is the top of
# its own git clone (not a plain directory inside some other repository) checked out
# at that commit. Content is always taken from that commit (git archive), never from
# the clone's working tree, so local edits there cannot leak into the output.
clone_at() {
  local dir=$THIRD_PARTY/$1 top got
  top=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null) || top=
  [ -n "$top" ] && [ "$(cd "$top" && pwd -P)" = "$(cd "$dir" && pwd -P)" ] \
    || { echo "FAILED: $dir is not a git clone (see $HERE/README.md)" >&2; exit 1; }
  got=$(git -C "$dir" rev-parse HEAD)
  [ "$got" = "$2" ] \
    || { echo "FAILED: $dir is at $got; the patch was made against $2" >&2; exit 1; }
  echo "$dir"
}

# new_tmp <output dir>: makes and prints a temporary directory beside the output,
# world-readable like a source directory (mktemp makes it 0700).
new_tmp() {
  local tmp
  tmp=$(mktemp -d "$1.tmp.XXXXXX")
  chmod 755 "$tmp"
  echo "$tmp"
}

# install_output <output dir> <tmp dir> <patch> <source lines>: applies the patch in the
# temporary directory, writes SOURCE.txt and replaces the output directory. No fuzz:
# a hunk whose context does not match exactly fails instead of landing nearby.
install_output() {
  local out=$1 tmp=$2 patchfile=$3 sources=$4
  patch -d "$tmp" -p1 --fuzz=0 --no-backup-if-mismatch --quiet < "$patchfile"
  {
    echo "Generated by SharedPtr/make_third_party.sh on $(date '+%Y-%m-%d %H:%M:%S %z'); do not edit."
    echo "$sources"
    echo "patched with $(basename "$patchfile"), md5 $(md5sum < "$patchfile" | cut -d' ' -f1)"
  } > "$tmp/SOURCE.txt"
  rm -rf "$out"
  mv "$tmp" "$out"
  echo "made $out"
}

# make_mm_hp: every file of the clone (sources, README, licenses), then mm_hp.patch.
make_mm_hp() {
  local hp tmp
  hp=$(clone_at HazardPtr "$HP_COMMIT")
  tmp=$(new_tmp "$HERE/mm_hp")
  git -C "$hp" archive HEAD | tar -x -C "$tmp"
  install_output "$HERE/mm_hp" "$tmp" "$HERE/mm_hp.patch" \
    "mm_hp: $hp at $HP_COMMIT (https://github.com/magedm/mm_hp)"
}

# make_parlay: all of ParlayLib's include/parlay/ (parlay/alloc.h pulls 13 of its
# headers; copying the whole directory needs no list), then the four upstream
# files the adapter needs -- not basic_atomic_shared_ptr.hpp (needs folly's
# hazptr), fast_shared_ptr.hpp, or upstream's atomic_shared_ptr.hpp (our adapter
# replaces it) -- then parlay.patch.
make_parlay() {
  local asp pl tmp f asp_paths=
  local asp_files="shared_ptr.hpp details/atomic_details.hpp details/hazard_pointers.hpp details/wait_free_counter.hpp"
  asp=$(clone_at AtomicSharedPtr "$ASP_COMMIT")
  pl=$(clone_at ParlayLib "$PARLAY_COMMIT")
  tmp=$(new_tmp "$HERE/lock_free_shared_ptr/parlay")
  # include/parlay/<file> in each clone lands at <file> in the output (strip 2).
  git -C "$pl" archive HEAD include/parlay | tar -x --strip-components=2 -C "$tmp"
  for f in $asp_files; do asp_paths="$asp_paths include/parlay/$f"; done
  # shellcheck disable=SC2086
  git -C "$asp" archive HEAD $asp_paths | tar -x --strip-components=2 -C "$tmp"
  install_output "$HERE/lock_free_shared_ptr/parlay" "$tmp" "$HERE/lock_free_shared_ptr/parlay.patch" \
    "ParlayLib include/parlay/: $pl at $PARLAY_COMMIT (https://github.com/cmuparlay/parlaylib)
AtomicSharedPtr $asp_files: $asp at $ASP_COMMIT (https://github.com/DanielLiamAnderson/atomic_shared_ptr)"
}

# Temporary directories left by a failed run are removed on exit.
trap 'rm -rf "$HERE"/mm_hp.tmp.* "$HERE"/lock_free_shared_ptr/parlay.tmp.*' EXIT

[ $# -eq 0 ] && set -- mm_hp parlay
# Every argument is checked before anything is made, so a run is all or nothing.
for what in "$@"; do
  case $what in
    mm_hp|parlay) ;;
    *) echo "usage: $0 [mm_hp] [parlay]" >&2; exit 1 ;;
  esac
done
for what in "$@"; do
  "make_$what"
done
